export const sidebarLinks = [
  {
    name: "Size",
    submenu: true,
    sublinks: [
      // { name: "xs", link: "/size/xs" },
      { name: "xs", link: "/" },
      { name: "s", link: "/" },
      { name: "m", link: "/" },
      { name: "l", link: "/" },
      { name: "xl", link: "/" },
      { name: "1x", link: "/" },
      { name: "2x", link: "/" },
      { name: "3x", link: "/" },
    ],
  },
  // {
  //   name:"color",
  //   submenu: true,
  //   sublinks: [
  //     { name: "Black", link: "/" },
  //     { name: "Brown", link: "/" },
  //     { name: "White", link: "/" },
  //     { name: "Blue", link: "/" },
  //     { name: "Grey", link: "/" },
  //     { name: "Green", link: "/" },
  //     { name: "Red", link: "/" },
  //     { name: "Pink", link: "/" },
  //     { name: "Ivory", link: "/" },
  //     { name: "Multi Color", link: "/" },
  //     { name: "Purple", link: "/" },
  //     { name: "Yellow", link: "/" },
  //     { name: "Orange", link: "/" },
  //     { name: "Nude", link: "/" },
  //     { name: "Silver", link: "/" },
  //     { name: "Gold", link: "/" }
  // ],
  // },
  {
    name: "color",
    submenu: true,
    sublinks: [
      { name: "Black", link: "/", bgColor: "#000000" },
      { name: "Brown", link: "/", bgColor: "#8B4513" },
      { name: "White", link: "/", bgColor: "#FFFFFF" },
      { name: "Blue", link: "/", bgColor: "#0000FF" },
      { name: "Grey", link: "/", bgColor: "#808080" },
      { name: "Green", link: "/", bgColor: "#008000" },
      { name: "Red", link: "/", bgColor: "#FF0000" },
      { name: "Pink", link: "/", bgColor: "#FFC0CB" },
      { name: "Ivory", link: "/", bgColor: "#FFFFF0" },
      {
        name: "Multi Color",
        link: "/",
        bgColor: "linear-gradient(90deg, #FF00FF, #FFFF00, #0000FF)",
      },
      { name: "Purple", link: "/", bgColor: "#800080" },
      { name: "Yellow", link: "/", bgColor: "#FFFF00" },
      { name: "Orange", link: "/", bgColor: "#FFA500" },
      { name: "Nude", link: "/", bgColor: "#F5CBA7" },
      { name: "Silver", link: "/", bgColor: "#C0C0C0" },
      { name: "Gold", link: "/", bgColor: "#FFD700" },
    ],
  },
  {
    name: "Style",
    submenu: true,
    sublinks: [
      // { name: "Tshirt", link: "/style/tshirt" },
      { name: "Tshirt", link: "/" },
      { name: "Pullover Sweater", link: "/" },
      { name: "Corset", link: "/" },
      { name: "Cardigan", link: "/" },
    ],
  },
  {
    name: "Occasion",
    submenu: true,
    sublinks: [
      // { name: "Everyday", link: "/occasion/everyday" },
      { name: "Everyday", link: "/" },
      { name: "Ski Resort", link: "/" },
      { name: "Streetwear", link: "/" },
      { name: "Office", link: "/" },
      { name: "Club", link: "/" },
      { name: "Date/Night", link: "/" },
    ],
  },
  {
    name: "Sleeve",
    submenu: true,
    sublinks: [
      // { name: "Long Sleeve", link: "/sleeve/long-sleeve" },
      { name: "Long Sleeve", link: "/" },
      { name: "Short Sleeve", link: "/" },
      { name: "Sleeveless", link: "/" },
      { name: "Strapless", link: "/" },
      { name: "Halter", link: "/" },
      { name: "Spaghetti Strap", link: "/" },
    ],
  },
  {
    name: "Fabric",
    submenu: true,
    sublinks: [
      // { name: "Cotton Blend", link: "/fabric/cotton-blend" },
      { name: "Cotton Blend", link: "/" },
      { name: "Acrylic Blend", link: "/" },
      { name: "Wool Blend", link: "/" },
      { name: "Linen Blend", link: "/" },
    ],
  },
  {
    name: "Length",
    submenu: true,
    sublinks: [
      // { name: "Regular", link: "/length/regular" },
      { name: "Regular", link: "/" },
      { name: "Cropped", link: "/" },
      { name: "Long", link: "/" },
    ],
  },
  {
    name: "Price",
    submenu: true,
    sublinks: [
      // { name: "$0-10", link: "/price/0-10" },
      { name: "$0-10", link: "/" },
      { name: "$10-25", link: "/" },
      { name: "$25-50", link: "/" },
      { name: "$50-75", link: "/" },
    ],
  },
];
